"""empty message

Revision ID: 3cec72a102bb
Revises: 
Create Date: 2021-08-08 08:44:12.859053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cec72a102bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('group_image', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('bg_color', sa.String(length=50), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('ended', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('caller', sa.Integer(), nullable=False),
    sa.Column('reciever', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caller'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reciever'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('friend', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], )
    )
    op.create_table('group_calls',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('groups',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('room_calls',
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('ended', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('ended', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('caller', sa.Integer(), nullable=False),
    sa.Column('reciever', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['caller'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reciever'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_mails')
    op.drop_table('room_calls')
    op.drop_table('groups')
    op.drop_table('group_calls')
    op.drop_table('contacts')
    op.drop_table('calls')
    op.drop_table('users')
    op.drop_table('rooms')
    # ### end Alembic commands ###
