"""empty message

Revision ID: 4cd0df5dc87f
Revises: 926c2609636f
Create Date: 2020-11-02 14:43:27.737663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd0df5dc87f'
down_revision = '926c2609636f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('ended', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('caller', sa.Integer(), nullable=False),
    sa.Column('reciever', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caller'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reciever'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_calls',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('room_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('ended', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('ended', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('caller', sa.Integer(), nullable=False),
    sa.Column('reciever', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['caller'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reciever'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rooms', sa.Column('category', sa.String(length=64), nullable=False))
    op.add_column('rooms', sa.Column('created_at', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('rooms', 'no_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('no_users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'category')
    op.drop_table('voice_mails')
    op.drop_table('room_calls')
    op.drop_table('group_calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
